runtime: custom
env: flex
resources:
        cpu: 1
        memory_gb: 2
        disk_size_gb: 10
readiness_check:
        path: "/readiness_check"
        check_interval_sec: 5
        timeout_sec: 4
        failure_threshold: 2
        success_threshold: 2
        app_start_timeout_sec: 500
